### ISSUE TITLE
Several issues and improvements

### ISSUE THREAD

**Issue by StfBauer** [patrick-rodgers/generator-sp-pnp-js-sample#1]
Hi,
there are several issues or improvements that can be in the documentations as well as the generator.

`npm install -g yo typings generator-sp-pnp-js-sample`

This will install all dependencies at once.

In general npm init is not required for yeoman generator because you deploy or create a package.json directly through the execution of the generator. In general it is easier to deploy the package.json right throught the installation of yeoman.

http://localhost:8080/ won't work in Office 365 because you need to have https. Otherwise the script won't be loaded.

The final consideration is that this yeoman generator is not suiteable nor useful. It is just a sample not a project template. In your case the easier and more apropriate method would have been to instruct the people to download this sample and how to use and install the node packages.

If I can help you with something let me know. ;)

**Comment by aandreassen** [comment]
I made this work in in Office 365 by modifying the webpack server in gulpfile.js to run on https:

```
    // Start a webpack-dev-server
    new server(webpack(serveConfig), {
        publicPath: serveConfig.output.publicPath,
        stats: {
            colors: true
        },
        https: true,
        contentBase: "dist"
    }).listen(443, "localhost", function(err) {
        if(err) throw new gutil.PluginError("serve", err);
        gutil.log("[serve]", "https://localhost:443/app.js");
    });
```

Also the reference to the application had to be updated to load correctly:

```
    <script type="text/javascript" 
          src="https://localhost:443/app.js" 
          data-divid="pnp-sample-container">
    </script>
   <div id="pnp-sample-container"></div>
```

**Comment by StfBauer** [comment]
@aandreassen I know how it works but I think it shouldn't it be a default by the generator ;) ?

**Comment by aandreassen** [comment]
But of course:-)

**Comment by patrick-rodgers** [comment]
Thanks for the feedback, I can make this update.

Also, to Stefan's point above - as mentioned on several of the calls that this is designed to be super simple to help get folks started, not really be the best generator in the world. If someone wanted to put together a "real" generator we would love to host in in PnP and spread the word. For example a react project, or a knockout. Keep in mind that the PG will be releasing generators with the launch of SP Fx as well.
